networks:
  bit-net:
    driver: bridge
  clear-net:
    driver: bridge

configs:
  bit-config:
    file: ./src/Bit/bit.conf

volumes:
  redis-master-data:
  grafana-storage:

services:
  bit1:
    build:
      context: ./src/
      dockerfile: Dockerfile
    networks:
      - bit-net
    depends_on:
      redis-master:
        condition: service_healthy
    environment:
      - bit_config=./app/bit-conf/bit.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  bit2:
    build:
      context: ./src/
      dockerfile: Dockerfile
    networks:
      - bit-net
    depends_on:
      redis-master:
        condition: service_healthy
    environment:
      - bit_config=./app/bit-conf/bit.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 10s
      retries: 3

  redis-master:
    image: redis:6.2
    command: redis-server --port 6379 --appendonly yes
    networks:
      - bit-net
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 3

  redis-replica1:
    build:
      context: ./docker/redis
      dockerfile: sentinel
    command: redis-server --port 6379 --slaveof redis-master 6379 --appendonly yes
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - bit-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-replica2:
    build:
      context: ./docker/redis
      dockerfile: sentinel
    command: redis-server --port 6379 --slaveof redis-master 6379 --appendonly yes
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - bit-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  sentinel1:
    build:
      context: ./docker/redis
      dockerfile: sentinel
    depends_on:
      redis-master:
        condition: service_healthy
    ports:
      - "26379:26379"
    networks:
      - bit-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  sentinel2:
    build:
      context: ./docker/redis
      dockerfile: sentinel
    depends_on:
      redis-master:
        condition: service_healthy
    ports:
      - "26380:26379"
    networks:
      - bit-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  sentinel3:
    build:
      context: ./docker/redis
      dockerfile: sentinel
    depends_on:
      redis-master:
        condition: service_healthy
    ports:
      - "26381:26379"
    networks:
      - bit-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.6
    ports:
      - "18888:18888"
      - "4317:18889"
    restart: unless-stopped

  nginx:
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - clear-net
      - bit-net
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bit1
      - bit2

